fix `@dataclass` subclasses of TestCase in 3.9
    TypeError: Can't instantiate abstract class TestConfig
    with abstract methods __hash__, __lt__

Because @dataclass does not have the ability to call an equivalent
of abc.update_abstractmethods(cls)...

https://github.com/python/cpython/issues/86071

Signed-off-by: Julia Vassiliki <julia.vassiliki@unsw.edu.au>